// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $greet_deleteResult from "./routes/greet/deleteResult.tsx";
import * as $greet_insertResult from "./routes/greet/insertResult.tsx";
import * as $greet_sResult from "./routes/greet/sResult.tsx";
import * as $greet_test from "./routes/greet/test.tsx";
import * as $greet_updateResult from "./routes/greet/updateResult.tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Delete from "./islands/Delete.tsx";
import * as $Home from "./islands/Home.tsx";
import * as $Insert from "./islands/Insert.tsx";
import * as $Search from "./islands/Search.tsx";
import * as $Test from "./islands/Test.tsx";
import * as $Update from "./islands/Update.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/greet/deleteResult.tsx": $greet_deleteResult,
    "./routes/greet/insertResult.tsx": $greet_insertResult,
    "./routes/greet/sResult.tsx": $greet_sResult,
    "./routes/greet/test.tsx": $greet_test,
    "./routes/greet/updateResult.tsx": $greet_updateResult,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Delete.tsx": $Delete,
    "./islands/Home.tsx": $Home,
    "./islands/Insert.tsx": $Insert,
    "./islands/Search.tsx": $Search,
    "./islands/Test.tsx": $Test,
    "./islands/Update.tsx": $Update,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
